# Generated by Django 5.1 on 2024-09-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexly', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
