# Generated by Django 5.0.6 on 2024-10-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexly', '0011_post_image_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetasPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='Nexly.post')),
            ],
        ),
    ]
